/*
 * generated by Xtext
 */
package com.rockwellcollins.serializer;

import com.google.inject.Inject;
import com.rockwellcollins.services.SpearGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class SpearSyntacticSequencer extends AbstractSyntacticSequencer {

	protected SpearGrammarAccess grammarAccess;
	protected AbstractElementAlias match_AtomicExpr_LeftParenthesisKeyword_10_0_a;
	protected AbstractElementAlias match_AtomicExpr_LeftParenthesisKeyword_10_0_p;
	protected AbstractElementAlias match_AtomicUnitExpr_LeftParenthesisKeyword_1_0_a;
	protected AbstractElementAlias match_AtomicUnitExpr_LeftParenthesisKeyword_1_0_p;
	protected AbstractElementAlias match_Definitions_ConstantsKeyword_5_0_q;
	protected AbstractElementAlias match_Definitions_ImportsKeyword_2_0_q;
	protected AbstractElementAlias match_Definitions_PatternsKeyword_6_0_q;
	protected AbstractElementAlias match_Definitions_TypesKeyword_4_0_q;
	protected AbstractElementAlias match_Definitions_UnitsKeyword_3_0_q;
	protected AbstractElementAlias match_Pattern_VarKeyword_11_0_q;
	protected AbstractElementAlias match_Specification_ConstantsKeyword_5_0_q;
	protected AbstractElementAlias match_Specification_ImportsKeyword_2_0_q;
	protected AbstractElementAlias match_Specification_MacrosKeyword_12_0_q;
	protected AbstractElementAlias match_Specification_PatternsKeyword_6_0_q;
	protected AbstractElementAlias match_Specification_StateKeyword_11_0_q;
	protected AbstractElementAlias match_Specification_TypesKeyword_4_0_q;
	protected AbstractElementAlias match_Specification_UnitsKeyword_3_0_q;
	protected AbstractElementAlias match_Specification___AssumptionsHeaderParserRuleCall_13_0_ColonKeyword_13_1__q;
	protected AbstractElementAlias match_Specification___PropertiesHeaderParserRuleCall_17_0_ColonKeyword_17_1__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (SpearGrammarAccess) access;
		match_AtomicExpr_LeftParenthesisKeyword_10_0_a = new TokenAlias(true, true, grammarAccess.getAtomicExprAccess().getLeftParenthesisKeyword_10_0());
		match_AtomicExpr_LeftParenthesisKeyword_10_0_p = new TokenAlias(true, false, grammarAccess.getAtomicExprAccess().getLeftParenthesisKeyword_10_0());
		match_AtomicUnitExpr_LeftParenthesisKeyword_1_0_a = new TokenAlias(true, true, grammarAccess.getAtomicUnitExprAccess().getLeftParenthesisKeyword_1_0());
		match_AtomicUnitExpr_LeftParenthesisKeyword_1_0_p = new TokenAlias(true, false, grammarAccess.getAtomicUnitExprAccess().getLeftParenthesisKeyword_1_0());
		match_Definitions_ConstantsKeyword_5_0_q = new TokenAlias(false, true, grammarAccess.getDefinitionsAccess().getConstantsKeyword_5_0());
		match_Definitions_ImportsKeyword_2_0_q = new TokenAlias(false, true, grammarAccess.getDefinitionsAccess().getImportsKeyword_2_0());
		match_Definitions_PatternsKeyword_6_0_q = new TokenAlias(false, true, grammarAccess.getDefinitionsAccess().getPatternsKeyword_6_0());
		match_Definitions_TypesKeyword_4_0_q = new TokenAlias(false, true, grammarAccess.getDefinitionsAccess().getTypesKeyword_4_0());
		match_Definitions_UnitsKeyword_3_0_q = new TokenAlias(false, true, grammarAccess.getDefinitionsAccess().getUnitsKeyword_3_0());
		match_Pattern_VarKeyword_11_0_q = new TokenAlias(false, true, grammarAccess.getPatternAccess().getVarKeyword_11_0());
		match_Specification_ConstantsKeyword_5_0_q = new TokenAlias(false, true, grammarAccess.getSpecificationAccess().getConstantsKeyword_5_0());
		match_Specification_ImportsKeyword_2_0_q = new TokenAlias(false, true, grammarAccess.getSpecificationAccess().getImportsKeyword_2_0());
		match_Specification_MacrosKeyword_12_0_q = new TokenAlias(false, true, grammarAccess.getSpecificationAccess().getMacrosKeyword_12_0());
		match_Specification_PatternsKeyword_6_0_q = new TokenAlias(false, true, grammarAccess.getSpecificationAccess().getPatternsKeyword_6_0());
		match_Specification_StateKeyword_11_0_q = new TokenAlias(false, true, grammarAccess.getSpecificationAccess().getStateKeyword_11_0());
		match_Specification_TypesKeyword_4_0_q = new TokenAlias(false, true, grammarAccess.getSpecificationAccess().getTypesKeyword_4_0());
		match_Specification_UnitsKeyword_3_0_q = new TokenAlias(false, true, grammarAccess.getSpecificationAccess().getUnitsKeyword_3_0());
		match_Specification___AssumptionsHeaderParserRuleCall_13_0_ColonKeyword_13_1__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getSpecificationAccess().getAssumptionsHeaderParserRuleCall_13_0()), new TokenAlias(false, false, grammarAccess.getSpecificationAccess().getColonKeyword_13_1()));
		match_Specification___PropertiesHeaderParserRuleCall_17_0_ColonKeyword_17_1__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getSpecificationAccess().getPropertiesHeaderParserRuleCall_17_0()), new TokenAlias(false, false, grammarAccess.getSpecificationAccess().getColonKeyword_17_1()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (ruleCall.getRule() == grammarAccess.getAssumptionsHeaderRule())
			return getAssumptionsHeaderToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getIdTypeDelimiterRule())
			return getIdTypeDelimiterToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getPropertiesHeaderRule())
			return getPropertiesHeaderToken(semanticObject, ruleCall, node);
		else if (ruleCall.getRule() == grammarAccess.getRequirementsHeaderRule())
			return getRequirementsHeaderToken(semanticObject, ruleCall, node);
		return "";
	}
	
	/**
	 * AssumptionsHeader:
	 * 	'Assumptions' | 'Environment'
	 * ;
	 */
	protected String getAssumptionsHeaderToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "Assumptions";
	}
	
	/**
	 * IdTypeDelimiter:
	 * 	':'
	 * 	| 'is a'
	 * 	| 'is an';
	 */
	protected String getIdTypeDelimiterToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return ":";
	}
	
	/**
	 * PropertiesHeader:
	 * 	'Requirements' | 'Properties' | 'Guarantees' | 'High-level Requirements' | 'HLRs'
	 * ;
	 */
	protected String getPropertiesHeaderToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "Requirements";
	}
	
	/**
	 * RequirementsHeader:
	 * 	'DerivedRequirements' | 'Requirements' | 'Low-Level Requirements' | 'LLRs' | 'Implementation' | 'Design'
	 * ;
	 */
	protected String getRequirementsHeaderToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		if (node != null)
			return getTokenText(node);
		return "DerivedRequirements";
	}
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_AtomicExpr_LeftParenthesisKeyword_10_0_a.equals(syntax))
				emit_AtomicExpr_LeftParenthesisKeyword_10_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AtomicExpr_LeftParenthesisKeyword_10_0_p.equals(syntax))
				emit_AtomicExpr_LeftParenthesisKeyword_10_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AtomicUnitExpr_LeftParenthesisKeyword_1_0_a.equals(syntax))
				emit_AtomicUnitExpr_LeftParenthesisKeyword_1_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_AtomicUnitExpr_LeftParenthesisKeyword_1_0_p.equals(syntax))
				emit_AtomicUnitExpr_LeftParenthesisKeyword_1_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Definitions_ConstantsKeyword_5_0_q.equals(syntax))
				emit_Definitions_ConstantsKeyword_5_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Definitions_ImportsKeyword_2_0_q.equals(syntax))
				emit_Definitions_ImportsKeyword_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Definitions_PatternsKeyword_6_0_q.equals(syntax))
				emit_Definitions_PatternsKeyword_6_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Definitions_TypesKeyword_4_0_q.equals(syntax))
				emit_Definitions_TypesKeyword_4_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Definitions_UnitsKeyword_3_0_q.equals(syntax))
				emit_Definitions_UnitsKeyword_3_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Pattern_VarKeyword_11_0_q.equals(syntax))
				emit_Pattern_VarKeyword_11_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Specification_ConstantsKeyword_5_0_q.equals(syntax))
				emit_Specification_ConstantsKeyword_5_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Specification_ImportsKeyword_2_0_q.equals(syntax))
				emit_Specification_ImportsKeyword_2_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Specification_MacrosKeyword_12_0_q.equals(syntax))
				emit_Specification_MacrosKeyword_12_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Specification_PatternsKeyword_6_0_q.equals(syntax))
				emit_Specification_PatternsKeyword_6_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Specification_StateKeyword_11_0_q.equals(syntax))
				emit_Specification_StateKeyword_11_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Specification_TypesKeyword_4_0_q.equals(syntax))
				emit_Specification_TypesKeyword_4_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Specification_UnitsKeyword_3_0_q.equals(syntax))
				emit_Specification_UnitsKeyword_3_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Specification___AssumptionsHeaderParserRuleCall_13_0_ColonKeyword_13_1__q.equals(syntax))
				emit_Specification___AssumptionsHeaderParserRuleCall_13_0_ColonKeyword_13_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Specification___PropertiesHeaderParserRuleCall_17_0_ColonKeyword_17_1__q.equals(syntax))
				emit_Specification___PropertiesHeaderParserRuleCall_17_0_ColonKeyword_17_1__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '#' ids+=[IdRef|ID]
	 *     (rule start) (ambiguity) 'after' after=TriggersExpr
	 *     (rule start) (ambiguity) 'if' cond=Expr
	 *     (rule start) (ambiguity) 'new' type=[ArrayTypeDef|ID]
	 *     (rule start) (ambiguity) 'new' type=[RecordTypeDef|ID]
	 *     (rule start) (ambiguity) 'previous' var=PrefixExpr
	 *     (rule start) (ambiguity) 'spec' spec=[Specification|ID]
	 *     (rule start) (ambiguity) 'while' cond=Expr
	 *     (rule start) (ambiguity) '|' ids+=[IdRef|ID]
	 *     (rule start) (ambiguity) id=[IdRef|ID]
	 *     (rule start) (ambiguity) op='-'
	 *     (rule start) (ambiguity) op='H'
	 *     (rule start) (ambiguity) op='O'
	 *     (rule start) (ambiguity) op='before'
	 *     (rule start) (ambiguity) op='historically'
	 *     (rule start) (ambiguity) op='initially'
	 *     (rule start) (ambiguity) op='never'
	 *     (rule start) (ambiguity) op='not'
	 *     (rule start) (ambiguity) op='once'
	 *     (rule start) (ambiguity) pattern=[Pattern|ID]
	 *     (rule start) (ambiguity) value=BOOL
	 *     (rule start) (ambiguity) value=INT
	 *     (rule start) (ambiguity) value=REAL
	 *     (rule start) (ambiguity) {ArrayAccessExpr.array=}
	 *     (rule start) (ambiguity) {ArrayUpdateExpr.access=}
	 *     (rule start) (ambiguity) {BinaryExpr.left=}
	 *     (rule start) (ambiguity) {RecordAccessExpr.record=}
	 *     (rule start) (ambiguity) {RecordUpdateExpr.record=}
	 */
	protected void emit_AtomicExpr_LeftParenthesisKeyword_10_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) 'after' after=TriggersExpr
	 *     (rule start) (ambiguity) 'previous' var=PrefixExpr
	 *     (rule start) (ambiguity) 'while' cond=Expr
	 *     (rule start) (ambiguity) op='-'
	 *     (rule start) (ambiguity) op='H'
	 *     (rule start) (ambiguity) op='O'
	 *     (rule start) (ambiguity) op='before'
	 *     (rule start) (ambiguity) op='historically'
	 *     (rule start) (ambiguity) op='initially'
	 *     (rule start) (ambiguity) op='never'
	 *     (rule start) (ambiguity) op='not'
	 *     (rule start) (ambiguity) op='once'
	 *     (rule start) (ambiguity) {ArrayAccessExpr.array=}
	 *     (rule start) (ambiguity) {ArrayUpdateExpr.access=}
	 *     (rule start) (ambiguity) {BinaryExpr.left=}
	 *     (rule start) (ambiguity) {RecordAccessExpr.record=}
	 *     (rule start) (ambiguity) {RecordUpdateExpr.record=}
	 */
	protected void emit_AtomicExpr_LeftParenthesisKeyword_10_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) unit=[UnitDef|ID]
	 *     (rule start) (ambiguity) {BinaryUnitExpr.left=}
	 */
	protected void emit_AtomicUnitExpr_LeftParenthesisKeyword_1_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) {BinaryUnitExpr.left=}
	 */
	protected void emit_AtomicUnitExpr_LeftParenthesisKeyword_1_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'Constants:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     imports+=Import 'Units:'? 'Types:'? (ambiguity) 'Patterns:' patterns+=Pattern
	 *     imports+=Import 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? (rule end)
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? (ambiguity) 'Patterns:' patterns+=Pattern
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? (rule end)
	 *     typedefs+=TypeDef (ambiguity) 'Patterns:' patterns+=Pattern
	 *     typedefs+=TypeDef (ambiguity) 'Patterns:'? (rule end)
	 *     unitdefs+=UnitDef 'Types:'? (ambiguity) 'Patterns:' patterns+=Pattern
	 *     unitdefs+=UnitDef 'Types:'? (ambiguity) 'Patterns:'? (rule end)
	 */
	protected void emit_Definitions_ConstantsKeyword_5_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'Imports:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID (ambiguity) 'Units:' unitdefs+=UnitDef
	 *     name=ID (ambiguity) 'Units:'? 'Types:' typedefs+=TypeDef
	 *     name=ID (ambiguity) 'Units:'? 'Types:'? 'Constants:' constants+=Constant
	 *     name=ID (ambiguity) 'Units:'? 'Types:'? 'Constants:'? 'Patterns:' patterns+=Pattern
	 *     name=ID (ambiguity) 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? (rule end)
	 */
	protected void emit_Definitions_ImportsKeyword_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'Patterns:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     constants+=Constant (ambiguity) (rule end)
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? (ambiguity) (rule end)
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? (ambiguity) (rule end)
	 *     typedefs+=TypeDef 'Constants:'? (ambiguity) (rule end)
	 *     unitdefs+=UnitDef 'Types:'? 'Constants:'? (ambiguity) (rule end)
	 */
	protected void emit_Definitions_PatternsKeyword_6_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'Types:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     imports+=Import 'Units:'? (ambiguity) 'Constants:' constants+=Constant
	 *     imports+=Import 'Units:'? (ambiguity) 'Constants:'? 'Patterns:' patterns+=Pattern
	 *     imports+=Import 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? (rule end)
	 *     name=ID 'Imports:'? 'Units:'? (ambiguity) 'Constants:' constants+=Constant
	 *     name=ID 'Imports:'? 'Units:'? (ambiguity) 'Constants:'? 'Patterns:' patterns+=Pattern
	 *     name=ID 'Imports:'? 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? (rule end)
	 *     unitdefs+=UnitDef (ambiguity) 'Constants:' constants+=Constant
	 *     unitdefs+=UnitDef (ambiguity) 'Constants:'? 'Patterns:' patterns+=Pattern
	 *     unitdefs+=UnitDef (ambiguity) 'Constants:'? 'Patterns:'? (rule end)
	 */
	protected void emit_Definitions_TypesKeyword_4_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'Units:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     imports+=Import (ambiguity) 'Types:' typedefs+=TypeDef
	 *     imports+=Import (ambiguity) 'Types:'? 'Constants:' constants+=Constant
	 *     imports+=Import (ambiguity) 'Types:'? 'Constants:'? 'Patterns:' patterns+=Pattern
	 *     imports+=Import (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? (rule end)
	 *     name=ID 'Imports:'? (ambiguity) 'Types:' typedefs+=TypeDef
	 *     name=ID 'Imports:'? (ambiguity) 'Types:'? 'Constants:' constants+=Constant
	 *     name=ID 'Imports:'? (ambiguity) 'Types:'? 'Constants:'? 'Patterns:' patterns+=Pattern
	 *     name=ID 'Imports:'? (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? (rule end)
	 */
	protected void emit_Definitions_UnitsKeyword_3_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'var'?
	 *
	 * This ambiguous syntax occurs at:
	 *     outputs+=Variable ')' (ambiguity) 'let' 'tel' (rule end)
	 *     outputs+=Variable ')' (ambiguity) 'let' assertions+=LustreAssertion
	 *     outputs+=Variable ')' (ambiguity) 'let' equations+=LustreEquation
	 *     outputs+=Variable ')' (ambiguity) 'let' properties+=LustreProperty
	 */
	protected void emit_Pattern_VarKeyword_11_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'Constants:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     imports+=Import 'Units:'? 'Types:'? (ambiguity) 'Patterns:' patterns+=Pattern
	 *     imports+=Import 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:' state+=Variable
	 *     imports+=Import 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:' macros+=Macro
	 *     imports+=Import 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     imports+=Import 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     imports+=Import 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     imports+=Import 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     imports+=Import 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' outputs+=Variable
	 *     imports+=Import 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' inputs+=Variable
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? (ambiguity) 'Patterns:' patterns+=Pattern
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:' state+=Variable
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:' macros+=Macro
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' outputs+=Variable
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' inputs+=Variable
	 *     typedefs+=TypeDef (ambiguity) 'Patterns:' patterns+=Pattern
	 *     typedefs+=TypeDef (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:' state+=Variable
	 *     typedefs+=TypeDef (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:' macros+=Macro
	 *     typedefs+=TypeDef (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     typedefs+=TypeDef (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     typedefs+=TypeDef (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     typedefs+=TypeDef (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     typedefs+=TypeDef (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' outputs+=Variable
	 *     typedefs+=TypeDef (ambiguity) 'Patterns:'? 'Inputs:' inputs+=Variable
	 *     units+=UnitDef 'Types:'? (ambiguity) 'Patterns:' patterns+=Pattern
	 *     units+=UnitDef 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:' state+=Variable
	 *     units+=UnitDef 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:' macros+=Macro
	 *     units+=UnitDef 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     units+=UnitDef 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     units+=UnitDef 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     units+=UnitDef 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     units+=UnitDef 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' 'Outputs:' outputs+=Variable
	 *     units+=UnitDef 'Types:'? (ambiguity) 'Patterns:'? 'Inputs:' inputs+=Variable
	 */
	protected void emit_Specification_ConstantsKeyword_5_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'Imports:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID (ambiguity) 'Units:' units+=UnitDef
	 *     name=ID (ambiguity) 'Units:'? 'Types:' typedefs+=TypeDef
	 *     name=ID (ambiguity) 'Units:'? 'Types:'? 'Constants:' constants+=Constant
	 *     name=ID (ambiguity) 'Units:'? 'Types:'? 'Constants:'? 'Patterns:' patterns+=Pattern
	 *     name=ID (ambiguity) 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:' state+=Variable
	 *     name=ID (ambiguity) 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:' macros+=Macro
	 *     name=ID (ambiguity) 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     name=ID (ambiguity) 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     name=ID (ambiguity) 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     name=ID (ambiguity) 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     name=ID (ambiguity) 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' outputs+=Variable
	 *     name=ID (ambiguity) 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' inputs+=Variable
	 */
	protected void emit_Specification_ImportsKeyword_2_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'Macros:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     constants+=Constant 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     constants+=Constant 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     constants+=Constant 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     constants+=Constant 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) AssumptionsHeader ':' assumptions+=Constraint
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) AssumptionsHeader ':' assumptions+=Constraint
	 *     inputs+=Variable 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     inputs+=Variable 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     inputs+=Variable 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     inputs+=Variable 'Outputs:' 'State:'? (ambiguity) AssumptionsHeader ':' assumptions+=Constraint
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) AssumptionsHeader ':' assumptions+=Constraint
	 *     outputs+=Variable 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     outputs+=Variable 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     outputs+=Variable 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     outputs+=Variable 'State:'? (ambiguity) AssumptionsHeader ':' assumptions+=Constraint
	 *     patterns+=Pattern 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     patterns+=Pattern 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     patterns+=Pattern 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     patterns+=Pattern 'Inputs:' 'Outputs:' 'State:'? (ambiguity) AssumptionsHeader ':' assumptions+=Constraint
	 *     state+=Variable (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     state+=Variable (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     state+=Variable (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     state+=Variable (ambiguity) AssumptionsHeader ':' assumptions+=Constraint
	 *     typedefs+=TypeDef 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     typedefs+=TypeDef 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     typedefs+=TypeDef 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     typedefs+=TypeDef 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) AssumptionsHeader ':' assumptions+=Constraint
	 *     units+=UnitDef 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     units+=UnitDef 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     units+=UnitDef 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     units+=UnitDef 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? (ambiguity) AssumptionsHeader ':' assumptions+=Constraint
	 */
	protected void emit_Specification_MacrosKeyword_12_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'Patterns:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     constants+=Constant (ambiguity) 'Inputs:' 'Outputs:' 'State:' state+=Variable
	 *     constants+=Constant (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:' macros+=Macro
	 *     constants+=Constant (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     constants+=Constant (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     constants+=Constant (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     constants+=Constant (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     constants+=Constant (ambiguity) 'Inputs:' 'Outputs:' outputs+=Variable
	 *     constants+=Constant (ambiguity) 'Inputs:' inputs+=Variable
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:' state+=Variable
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:' macros+=Macro
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' outputs+=Variable
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' inputs+=Variable
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:' state+=Variable
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:' macros+=Macro
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' outputs+=Variable
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' inputs+=Variable
	 *     typedefs+=TypeDef 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:' state+=Variable
	 *     typedefs+=TypeDef 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:' macros+=Macro
	 *     typedefs+=TypeDef 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     typedefs+=TypeDef 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     typedefs+=TypeDef 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     typedefs+=TypeDef 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     typedefs+=TypeDef 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' outputs+=Variable
	 *     typedefs+=TypeDef 'Constants:'? (ambiguity) 'Inputs:' inputs+=Variable
	 *     units+=UnitDef 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:' state+=Variable
	 *     units+=UnitDef 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:' macros+=Macro
	 *     units+=UnitDef 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     units+=UnitDef 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     units+=UnitDef 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     units+=UnitDef 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     units+=UnitDef 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' 'Outputs:' outputs+=Variable
	 *     units+=UnitDef 'Types:'? 'Constants:'? (ambiguity) 'Inputs:' inputs+=Variable
	 */
	protected void emit_Specification_PatternsKeyword_6_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'State:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     constants+=Constant 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:' macros+=Macro
	 *     constants+=Constant 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     constants+=Constant 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     constants+=Constant 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     constants+=Constant 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:' macros+=Macro
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     inputs+=Variable 'Outputs:' (ambiguity) 'Macros:' macros+=Macro
	 *     inputs+=Variable 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     inputs+=Variable 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     inputs+=Variable 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     inputs+=Variable 'Outputs:' (ambiguity) 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:' macros+=Macro
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     outputs+=Variable (ambiguity) 'Macros:' macros+=Macro
	 *     outputs+=Variable (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     outputs+=Variable (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     outputs+=Variable (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     outputs+=Variable (ambiguity) 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     patterns+=Pattern 'Inputs:' 'Outputs:' (ambiguity) 'Macros:' macros+=Macro
	 *     patterns+=Pattern 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     patterns+=Pattern 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     patterns+=Pattern 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     patterns+=Pattern 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     typedefs+=TypeDef 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:' macros+=Macro
	 *     typedefs+=TypeDef 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     typedefs+=TypeDef 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     typedefs+=TypeDef 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     typedefs+=TypeDef 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     units+=UnitDef 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:' macros+=Macro
	 *     units+=UnitDef 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     units+=UnitDef 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     units+=UnitDef 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     units+=UnitDef 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' (ambiguity) 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 */
	protected void emit_Specification_StateKeyword_11_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'Types:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     imports+=Import 'Units:'? (ambiguity) 'Constants:' constants+=Constant
	 *     imports+=Import 'Units:'? (ambiguity) 'Constants:'? 'Patterns:' patterns+=Pattern
	 *     imports+=Import 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:' state+=Variable
	 *     imports+=Import 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:' macros+=Macro
	 *     imports+=Import 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     imports+=Import 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     imports+=Import 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     imports+=Import 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     imports+=Import 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' outputs+=Variable
	 *     imports+=Import 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' inputs+=Variable
	 *     name=ID 'Imports:'? 'Units:'? (ambiguity) 'Constants:' constants+=Constant
	 *     name=ID 'Imports:'? 'Units:'? (ambiguity) 'Constants:'? 'Patterns:' patterns+=Pattern
	 *     name=ID 'Imports:'? 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:' state+=Variable
	 *     name=ID 'Imports:'? 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:' macros+=Macro
	 *     name=ID 'Imports:'? 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     name=ID 'Imports:'? 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     name=ID 'Imports:'? 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     name=ID 'Imports:'? 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     name=ID 'Imports:'? 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' outputs+=Variable
	 *     name=ID 'Imports:'? 'Units:'? (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' inputs+=Variable
	 *     units+=UnitDef (ambiguity) 'Constants:' constants+=Constant
	 *     units+=UnitDef (ambiguity) 'Constants:'? 'Patterns:' patterns+=Pattern
	 *     units+=UnitDef (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:' state+=Variable
	 *     units+=UnitDef (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:' macros+=Macro
	 *     units+=UnitDef (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     units+=UnitDef (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     units+=UnitDef (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     units+=UnitDef (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     units+=UnitDef (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' outputs+=Variable
	 *     units+=UnitDef (ambiguity) 'Constants:'? 'Patterns:'? 'Inputs:' inputs+=Variable
	 */
	protected void emit_Specification_TypesKeyword_4_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     'Units:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     imports+=Import (ambiguity) 'Types:' typedefs+=TypeDef
	 *     imports+=Import (ambiguity) 'Types:'? 'Constants:' constants+=Constant
	 *     imports+=Import (ambiguity) 'Types:'? 'Constants:'? 'Patterns:' patterns+=Pattern
	 *     imports+=Import (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:' state+=Variable
	 *     imports+=Import (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:' macros+=Macro
	 *     imports+=Import (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     imports+=Import (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     imports+=Import (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     imports+=Import (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     imports+=Import (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' outputs+=Variable
	 *     imports+=Import (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' inputs+=Variable
	 *     name=ID 'Imports:'? (ambiguity) 'Types:' typedefs+=TypeDef
	 *     name=ID 'Imports:'? (ambiguity) 'Types:'? 'Constants:' constants+=Constant
	 *     name=ID 'Imports:'? (ambiguity) 'Types:'? 'Constants:'? 'Patterns:' patterns+=Pattern
	 *     name=ID 'Imports:'? (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:' state+=Variable
	 *     name=ID 'Imports:'? (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:' macros+=Macro
	 *     name=ID 'Imports:'? (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     name=ID 'Imports:'? (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     name=ID 'Imports:'? (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' requirements+=Constraint
	 *     name=ID 'Imports:'? (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? AssumptionsHeader ':' assumptions+=Constraint
	 *     name=ID 'Imports:'? (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' outputs+=Variable
	 *     name=ID 'Imports:'? (ambiguity) 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' inputs+=Variable
	 */
	protected void emit_Specification_UnitsKeyword_3_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (AssumptionsHeader ':')?
	 *
	 * This ambiguous syntax occurs at:
	 *     constants+=Constant 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     constants+=Constant 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     constants+=Constant 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' requirements+=Constraint
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' requirements+=Constraint
	 *     inputs+=Variable 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     inputs+=Variable 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     inputs+=Variable 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' requirements+=Constraint
	 *     macros+=Macro (ambiguity) RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     macros+=Macro (ambiguity) RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     macros+=Macro (ambiguity) RequirementsHeader ':' requirements+=Constraint
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' requirements+=Constraint
	 *     outputs+=Variable 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     outputs+=Variable 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     outputs+=Variable 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' requirements+=Constraint
	 *     patterns+=Pattern 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     patterns+=Pattern 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     patterns+=Pattern 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' requirements+=Constraint
	 *     state+=Variable 'Macros:'? (ambiguity) RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     state+=Variable 'Macros:'? (ambiguity) RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     state+=Variable 'Macros:'? (ambiguity) RequirementsHeader ':' requirements+=Constraint
	 *     typedefs+=TypeDef 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     typedefs+=TypeDef 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     typedefs+=TypeDef 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' requirements+=Constraint
	 *     units+=UnitDef 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' (PropertiesHeader ':')? (rule end)
	 *     units+=UnitDef 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' PropertiesHeader ':' behaviors+=Constraint
	 *     units+=UnitDef 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (ambiguity) RequirementsHeader ':' requirements+=Constraint
	 */
	protected void emit_Specification___AssumptionsHeaderParserRuleCall_13_0_ColonKeyword_13_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     (PropertiesHeader ':')?
	 *
	 * This ambiguous syntax occurs at:
	 *     assumptions+=Constraint RequirementsHeader ':' (ambiguity) (rule end)
	 *     constants+=Constant 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (ambiguity) (rule end)
	 *     imports+=Import 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (ambiguity) (rule end)
	 *     inputs+=Variable 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (ambiguity) (rule end)
	 *     macros+=Macro (AssumptionsHeader ':')? RequirementsHeader ':' (ambiguity) (rule end)
	 *     name=ID 'Imports:'? 'Units:'? 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (ambiguity) (rule end)
	 *     outputs+=Variable 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (ambiguity) (rule end)
	 *     patterns+=Pattern 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (ambiguity) (rule end)
	 *     requirements+=Constraint (ambiguity) (rule end)
	 *     state+=Variable 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (ambiguity) (rule end)
	 *     typedefs+=TypeDef 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (ambiguity) (rule end)
	 *     units+=UnitDef 'Types:'? 'Constants:'? 'Patterns:'? 'Inputs:' 'Outputs:' 'State:'? 'Macros:'? (AssumptionsHeader ':')? RequirementsHeader ':' (ambiguity) (rule end)
	 */
	protected void emit_Specification___PropertiesHeaderParserRuleCall_17_0_ColonKeyword_17_1__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
