/*
 * generated by Xtext
 */
package com.rockwellcollins.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

import com.google.inject.Inject;
import com.rockwellcollins.services.SpearGrammarAccess;

/**
 * This class contains custom formatting declarations.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#
 * formatting on how and when to use it.
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an
 * example
 */
public class SpearFormatter extends AbstractDeclarativeFormatter {

	@Inject
	private SpearGrammarAccess g;

	@Override
	protected void configureFormatting(FormattingConfig c) {
		//wrap lines at 120
		c.setAutoLinewrap(120);
		
		//adjust spacing after punctuation
		g.findKeywords(",").forEach(comma -> c.setNoSpace().before(comma));
		g.findKeywords(":").forEach(semi -> c.setNoSpace().before(semi));
		g.findKeywords(".").forEach(period -> c.setNoSpace().around(period));
		g.findKeywords("(").forEach(op -> c.setNoSpace().after(op));
		g.findKeywords(")").forEach(cp -> c.setNoSpace().before(cp));
		
	}
}
