/*
 * generated by Xtext 2.18.0.M3
 */
package com.rockwellcollins;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class SpearStandaloneSetup extends SpearStandaloneSetupGenerated {

	public static void doSetup() {
		new SpearStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
