/*
 * Information: Initially generated by Xtext 2.18.0.M3
 */
package com.rockwellcollins.ui.quickfix;

import org.eclipse.xtext.ui.editor.model.IXtextDocument;
import org.eclipse.xtext.ui.editor.model.edit.IModification;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;

import com.rockwellcollins.validation.SpearValidator;

/**
 * Custom quickfixes.
 *
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
public class SpearQuickfixProvider extends DefaultQuickfixProvider {

	@Fix(SpearValidator.INVALID_ASSUMPTION_REF)
	public void provideInputIds(final Issue issue, IssueResolutionAcceptor acceptor) {
		for (String replacement : issue.getData()) {
			acceptor.accept(issue, "Change to " + replacement, null, null, new IModification() {
				@Override
				public void apply(IModificationContext context) throws Exception {
					IXtextDocument xtextDocument = context.getXtextDocument();
					xtextDocument.replace(issue.getOffset(), issue.getLength(), replacement);
				}
			});
		}
	}

	@Fix(SpearValidator.MISMATCHED_FILENAME)
	public void provideBaseFilename(final Issue issue, IssueResolutionAcceptor acceptor) {
		for (String replacement : issue.getData()) {
			acceptor.accept(issue, "Change to " + replacement, null, null, new IModification() {
				@Override
				public void apply(IModificationContext context) throws Exception {
					IXtextDocument xtextDocument = context.getXtextDocument();
					xtextDocument.replace(issue.getOffset(), issue.getLength(), replacement);
				}
			});
		}
	}

}
